name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  build_and_run_selenium_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Start containers
      run: |
        docker-compose -f "docker-compose.yml" up -d --build
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt;
    - name: Sleep for 15s
      uses: juliangruber/sleep-action@v1
      with:
        time: 15s
    - name: Check hub status
      run: |
        curl -L http://localhost:4444/grid/api/hub
    - name: Run selenium pytest
      env:
        PASSWORD_GIT_TEST: ${{ secrets.PASSWORD_GIT_TEST }}
        EMAIL_GIT_TEST: ${{ secrets.EMAIL_GIT_TEST }}
        USER_GIT_TEST: ${{ secrets.USER_GIT_TEST }}
      run: |
        pytest -v --html=report.html --self-contained-html
    - name: Stop containers
      if: always()
      run: |
        docker-compose -f "docker-compose.yml" down
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: artifact-with-test-results
        path: ${{ github.workspace }}/tests/reports
    - name: Check dirs
      if: always()
      run: |
        ls /home/runner/work/my-selenium-python-dojo/my-selenium-python-dojo/
