name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt;
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install Firefox
      run: |
        sudo apt install firefox
    - name: Run selenium pytest
      env:
        PASSWORD_GIT_TEST: ${{ secrets.PASSWORD_GIT_TEST }}
        EMAIL_GIT_TEST: ${{ secrets.EMAIL_GIT_TEST }}
        USER_GIT_TEST: ${{ secrets.USER_GIT_TEST }}
      run: |
         pytest --html=report.html --self-contained-html
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: my-artifact
        path: /home/runner/work/my-selenium-python-dojo/my-selenium-python-dojo
