name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install webdriver-manager
        pip install selenium
        pip install msedge-selenium-tools selenium==3.141
        pip install PyHamcrest
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Make sure pytest is working
      run: |
        echo "def test_1(): pass" > nothing.py
        pytest nothing.py
    - name: Check secret
      env:
        SUPER_SECRET: ${{ secrets.EMAIL_GIT_TEST }}
      run: |
        echo $SUPER_SECRET
    - name: Run selenium pytest
      run: |
        pytest tests/secret_test.py
