name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:14.4
      options: --network-alias testHost
      env:
        SELENIUM_HUB_HOST: hub
        TEST_HOST: testhost
    services:
      hub:
        image: selenium/hub:latest
      chrome:
        image: selenium/node-chrome:latest
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
    - name: Install dependencies
      run: |
        curl http://testhost:4444/wd/hub/status/