name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install webdriver-manager
        pip install selenium
        pip install msedge-selenium-tools selenium==3.141
        pip install PyHamcrest
        pip install chromedriver-py
        pip install pytest-html
        pip install pytest-html-reporter
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Make sure pytest is working
      run: |
        echo "def test_1(): pass" > nothing.py
        pytest nothing.py
    - name: Run selenium pytest
      env:
        EMAIL_GIT_TEST: ${{ secrets.EMAIL_GIT_TEST }}
        USER_GIT_TEST: ${{ secrets.USER_GIT_TEST }}
        PASSWORD_GIT_TEST: ${{ secrets.PASSWORD_GIT_TEST }}
      run: |
        pytest tests/
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: my-artifact
        path: /home/runner/work/my-selenium-python-example/my-selenium-python-example/tests
