name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Start containers
      run: |
        docker-compose -f "docker-compose.yml" up -d --build
    - name: Sleep for 60s
      uses: juliangruber/sleep-action@v1
      with:
        time: 60s
    - name: Check hub status
      run: |
        curl -L http://localhost:4444/grid/api/hub
    - name: Stop containers
      if: always()
      run: |
        docker-compose -f "docker-compose.yml" down