name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Start containers
      run: |
      docker-compose -f "docker-compose.yml" up -d --build
    - name: Check hub status
      run: |
      sh curl http://localhost:4444/wd/hub/status/
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down